### ISSUE TITLE
Typo "sepc" -> "spec" in Deployment YAML file

### ISSUE THREAD

**Issue by xaviatwork** [meshcloud/unipipe-service-broker#117]
There's a typo in the [Deployment YAML file](https://github.com/meshcloud/unipipe-service-broker/wiki/How-To-Guides#manually-deploy-a-azure-container-group-for-unipipe-service-broker--caddy-ssl)

```yaml
...
 resources:
        requests:                 # you can sepc the container resource according your need
...
```

I think it should be "spec" and not "sepc"
